[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags =
    -D MT_DEBUGGING
lib_deps =
    https://github.com/meshtastic/Meshtastic-arduino.git#6edd5643
    siara-cc/Sqlite3Esp32